# Testing library
enable_testing()

function(add_doctest name)
  set(options) # unused
  set(oneValueArgs)
  set(multiValueArgs SRCS)
  cmake_parse_arguments(ARG "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

  add_executable(${name} ${ARG_SRCS})
  target_compile_features(${name} PRIVATE cxx_std_23)

  # Include paths
  target_include_directories(${name} PRIVATE ../include)

  # Libraries (common for all tests)
  target_link_libraries(${name} PRIVATE pdfguard podofo)

  # Register with CTest
  add_test(NAME ${name} COMMAND ${name})
endfunction()
add_doctest(test_pdf_guard SRCS test_pdf_guard.cpp)
add_doctest(test_watermark SRCS test_watermark.cpp)
add_doctest(test_font_params SRCS test_font_params.cpp)
add_doctest(test_pdf_file SRCS test_pdf_file.cpp)
